name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ip:
        description: 'lan ip'
        required: false
        default: '192.168.1.1'
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Send greeting
      run: |
        echo "${{ github.event.inputs.ip }}"
        touch test
        echo "${{ github.event.inputs.ip }}" >> test
        echo "test1" >> test1
        
        sed -i 's/192.168.1.1/192.168.50.5/g' test
        sed -i 's/test1/${{ github.event.inputs.ip }}/g' test1
        
        echo "===cat test==="
        cat test
        
        echo "===cat test1==="
        cat test1
        
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
